FROM registry.fedoraproject.org/fedora:latest AS builder

RUN dnf install -y gcc musl-gcc musl-libc-static && dnf clean all
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup target add x86_64-unknown-linux-musl

ENV K8S_OPENAPI_ENABLED_VERSION=1.32

WORKDIR /build
COPY . .

RUN cargo build --release --target x86_64-unknown-linux-musl --features "cloud-hypervisor,qemu,kubevirt,aggregator"

FROM scratch

COPY --from=builder /build/target/x86_64-unknown-linux-musl/release/vbmc-rs /vbmc-rs
COPY --from=builder /build/target/x86_64-unknown-linux-musl/release/vbmc-rs-aggregator /vbmc-rs-aggregator

EXPOSE 8000
ENTRYPOINT ["/vbmc-rs"]
CMD ["-c", "/etc/vbmc-rs/config.toml"]
