FROM registry.fedoraproject.org/fedora:latest AS builder

RUN dnf install -y gcc libvirt-devel && dnf clean all
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /build
COPY . .

RUN cargo build --release --features "cloud-hypervisor,qemu,libvirt"

FROM registry.fedoraproject.org/fedora-minimal:latest

RUN microdnf install -y libvirt-libs && microdnf clean all

COPY --from=builder /build/target/release/vbmc-rs /usr/local/bin/vbmc-rs

EXPOSE 8000
ENTRYPOINT ["/usr/local/bin/vbmc-rs"]
CMD ["-c", "/etc/vbmc-rs/config.toml"]
